#+BEGIN_COMMENT
.. title: Getting Your Feet Wet
.. slug: getting-your-feet-wet
.. date: 2018-05-26 15:45:39 UTC-07:00
.. tags: tensorflow dummies
.. category: TensorFlow
.. link: 
.. description: A hello world for tensorflow.
.. type: text
#+END_COMMENT

* Hello
This is a [[https://en.wikipedia.org/wiki/%22Hello,_World!%22_program][hello-world]] for tensorflow, it will create a tensor with our message and then print it when the graph is executed.
** Import
  We're just going to import [[https://www.tensorflow.org/][tensorflow]].
#+BEGIN_SRC ipython :session hello :results none
import tensorflow
#+END_SRC

** Create the Tensor
  We're going to use [[https://www.tensorflow.org/api_docs/python/tf/string_join][=string_join=]] which takes a lists of strings (it will consider each one a separate [[https://www.tensorflow.org/programmers_guide/tensors][tensor]]) and creates a single [[https://en.wikipedia.org/wiki/Tensor][tensor]] that we're going to store in the =message= variable.
#+BEGIN_SRC ipython :session hello :results none
message = tensorflow.string_join(['Hello ', 'TensorFlow!'])
#+END_SRC

** Running the Session
  When you create a tensor it doesn't execute the calculations, it just defines what is going to be used to run the execution. To actually execute it you need to create a [[https://www.tensorflow.org/api_docs/python/tf/Session][Session]] and then [[https://www.tensorflow.org/api_docs/python/tf/Session#run][run]] it.

#+BEGIN_SRC ipython :session hello :results output
with tensorflow.Session() as session:
    print(session.run(message))
#+END_SRC

#+BEGIN_EXAMPLE
: b'Hello TensorFlow!'
#+END_EXAMPLE

The first argument to =run= can be any single graph element or list of graph elements that you want tensorflow to execute.
* Style
  Google has a [[https://www.tensorflow.org/community/style_guide][style guide]] specifically for TensorFlow. It says that you should follow the [[https://pep8.readthedocs.io/en/release-1.7.x/][PEP 8]] style guide except where they think they know better. The exceptions are:

  - 2 spaces instead of 4 for indentation
  - Make everything compatible with both python 2 and 3

This means that every file should have these imports in them:

#+BEGIN_SRC python
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
#+END_SRC

And you should use [[https://pythonhosted.org/six/][six]] or something like it to make other compatibility changes.
