#+BEGIN_COMMENT
.. title: Logging, Multiple Graphs, Summaries, and Saving Graphs
.. slug: logging-multiple-graphs-summaries-and-saving-graphs
.. date: 2018-05-29 14:30:05 UTC-07:00
.. tags: tensorflow dummies
.. category: TensorFlow
.. link: 
.. description: How to use logging, create multiple graphs, summarize graphs and save them.
.. type: text
#+END_COMMENT

This is based on *TensorFlow for Dummies* and the TensorFlow documentation.

* What is this about?
  This will demonstrate serveral things that might be commonly useful:

  - How to use logging
  - How to create multiple graphs
  - How to summarize graphs
  - How to save graphs to a file

#+BEGIN_SRC ipython :session dummies
import tensorflow
#+END_SRC

* How do you use logging?
  The [[https://www.tensorflow.org/api_docs/python/tf/logging][TensorFlow logging]] looks a lot like the regular [[https://docs.python.org/3.5/library/logging.html][python logging]] with some notable helpful additions - you can have print conditionally, you can have it print only a certain number of times, and you can have it print once every so many times that it's called. To enable it you set its verbosity level with the [[https://www.tensorflow.org/api_docs/python/tf/logging/set_verbosity][set_verbosity]] function.

#+BEGIN_SRC ipython :session dummies :exports both :results output
tensorflow.logging.set_verbosity(logging.)
#+END_SRC
